
export const testKata: Kata = {
	id: "55bf01e5a717a0d57e0000ec",
	name: "Disemvowel Trolls",
	slug: "disemvowel-trolls",
	category: "reference",
	publishedAt: "2014-02-12T16:54:28.937Z",
	approvedAt: "2014-02-17T22:17:12.516Z",
	languages: [
		"coffeescript",
		"javascript",
		"python",
		"ruby",
		"clojure",
		"haskell",
		"csharp",
		"fsharp",
		"shell",
		"swift",
		"typescript",
		"java",
		"cpp",
		"c",
		"julia",
		"lua",
		"elixir",
		"factor",
		"rust",
		"crystal",
		"nasm",
		"perl",
		"r",
	],
	url: "https://www.codewars.com/kata/52fba66badcd10859f00097e",
	rank: {
		id: -7,
		name: "7 kyu",
		color: "white",
	},
	createdAt: "2014-02-12T16:50:52.989Z",
	createdBy: {
		username: "osuushi",
		url: "https://www.codewars.com/users/osuushi",
	},
	approvedBy: {
		username: "jhoffner",
		url: "https://www.codewars.com/users/jhoffner",
	},
	description:
		'Trolls are attacking your comment section!\n\nA common way to deal with this situation is to remove all of the vowels from the trolls\' comments, neutralizing the threat.\n\nYour task is to write a function that takes a string and return a new string with all vowels removed.\n\nFor example, the string "This website is for losers LOL!" would become "Ths wbst s fr lsrs LL!".\n\nNote: for this kata `y` isn\'t considered a vowel.\n',
	totalAttempts: 666196,
	totalCompleted: 218936,
	totalStars: 2097,
	voteScore: 16844,
	tags: ["Strings", "Regular Expressions", "Fundamentals"],
	contributorsWanted: true,
	unresolved: {
		issues: 4,
		suggestions: 3,
	},
};